### ISSUE TITLE
Profile Feed

### ISSUE THREAD

**Issue by themikail** [themikail/capstone_project#16]
**Value proposition**
The Profile button allows users to access and manage their 
Spotify-related information within the Navbar application, 
providing a seamless and personalized experience.

**Description**
![Bildschirmfoto 2023-06-05 um 09 55 44](https://github.com/themikail/capstone_project/assets/66737755/d4405284-c300-48be-a20c-6b8da6681e77)

**Acceptance criteria**

Profile Button Creation

Given that I am using the Navbar application,
When I navigate to the home screen,
Then I should see a "Profile" button in the navigation bar.

Opening Profile Page

Given that I am on the home screen of the Navbar application,
When I tap on the "Profile" button in the navigation bar,
Then a new page named "Profile" should be opened, displaying my Spotify information.

Automatic Population of Spotify Information

Given that I am on the "Profile" page of the Navbar application,
When the page is loaded,
Then the page should automatically populate my Spotify-related information, such as my name and profile picture, from the Spotify API.

Changing Profile Picture

Given that I am on the "Profile" page of the Navbar application,
When I tap on the "Change Profile Picture" button,
Then I should be able to select a new profile picture from my device's photo library,
And my profile picture should be updated accordingly.

Changing Name

Given that I am on the "Profile" page of the Navbar application,
When I tap on the "Edit Name" button,
Then I should be able to edit my name in a text input field,
And when I save the changes, my name should be updated accordingly

**Tasks**

- [ ] Add a "Profile" button to the navigation bar on the home screen.
- [ ] Create a new page named "Profile" with the necessary layout and design.
- [ ] Integrate with the Spotify API to fetch the user's Spotify-related information.
- [ ] Implement the automatic population of the Spotify information on the "Profile" page.
- [ ] Develop the "Change Profile Picture" functionality, allowing users to select a new picture from their device's photo library.
- [ ] Update the profile picture on the "Profile" page and synchronize the change across the application.
- [ ] Implement the "Edit Name" feature, providing users with a text input field to modify their name.
- [ ] Save the changes made to the name and ensure it is reflected across the entire application.
